version: '3.3'
services:
  nginx:
    image: nginx:latest
    ports:
      - 8080:80
    depends_on:
      - php
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

  php:
    build: ./docker/php/
    volumes:
      - .:/var/www/html
      - ./docker/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini
    depends_on:
      - db
      - redis
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=db"
      - "DB_USERNAME=root"
      - "DB_NAME=mycoolapp_dev"
      - "DB_PASS=secret"

  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=mycoolapp_dev
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_USER=root
      - MYSQL_PASSWORD=secret

  redis:
    image: redis:4.0
    ports:
      - "6382:6379"

  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
    - REDIS_HOSTS=local:redis:6379
    ports:
    - "8081:8081"

  adminer:
    image: adminer
    depends_on:
      - db
    ports:
      - 8082:8080
    environment:
      ADMINER_DEFAULT_SERVER: db

volumes:
  db_data:
