version: '3.3'
services:
  nginx:
    image: nginx:1.17.4-alpine
    ports:
      - 8989:80
    depends_on:
      - php
    volumes:
      - .:/application
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

  php:
    build: ./docker/php/
    volumes:
      - .:/application
      - ./docker/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini
    depends_on:
      - db
      - redis
    environment:
      - DB_PORT=3306
      - DB_HOST=db
      - DB_USERNAME=root
      - DB_PASS=secret
      - DB_NAME=app_db


  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=app_db
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_USER=root
      - MYSQL_PASSWORD=secret

  redis:
    image: redis:5.0.6-alpine
    ports:
      - "6382:6379"

  adminer:
    image: adminer:4.2.5-standalone
    ports:
      - 8080:8080

volumes:
  db_data:
